#!/usr/bin/env bash
set -e -u -x

# Configurations
GHUSER=${GHUSER:-skatsuta}
REPO=${REPO:-ansible-osx}
DEST=${DEST:-${HOME}/src/github.com/${GHUSER}}
SSH_KEY_TYPE=${SSH_KEY_TYPE:-ed25519}
SSH_KEY_PATH=$HOME/.ssh/id_$SSH_KEY_TYPE


# Show variables
show_variables() {
  echo "Configurations:"
  echo "    - Username:     ${GHUSER}"
  echo "    - Repository:   ${REPO}"
  echo "    - Destination:  ${DEST}"
  echo "    - SSH key type: ${SSH_KEY_TYPE}"
}


# Generate SSH Key
generate_ssh_key() {
  if [[ -f "$SSH_KEY_PATH" ]]; then
    echo "Your SSH key already exists."
    return
  fi

  echo "Generating a SSH key..."
  ssh-keygen -t "$SSH_KEY_TYPE"

  echo "Adding your SSH key to the ssh-agent..."
  eval "$(ssh-agent -s)"
  ssh-add 
}

# Prompt the confirmation of adding the SSH key to GitHub
prompt_confirmation() {
  echo "You should add the generated key to GitHub before proceeding."
  while true; do
    read -p "Are you sure you want to proceed? [Yn] " yn
    case $yn in
      [Yy]*|'')
        echo "Proceeding..."
        break
        ;;
      [Nn]*)
        echo "Stopped."
        exit 1
        ;;
    esac
  done
}

# Install Xcode
install_xcode() {
  if [[ -d /Library/Developer/CommandLineTools ]]; then
    echo "Xcode is already installed."
    return
  fi

  echo "Install Xcode..."
  echo "*** If a dialog is shown,\
    push 'Get Xcode' button to download Xcode before proceeding! ***"
  sudo xcodebuild -license
  xcode-select --install
}

# Install Homebrew
install_homebrew() {
  if [[ -f /usr/local/bin/brew ]]; then
    echo "Homebrew is already installed."
    return
  fi

  echo "Install Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "Run 'brew doctor'..."
  brew doctor
}

# Install packages for running Ansible playbook
install_packages_for_ansible() {
  echo "Install packages for running Ansible..."
  brew install git python ansible
}

# Clone my GitHub repository
clone_repo() {
  if [[ -d ${DEST}/${REPO} ]]; then
    echo "Repository is already cloned."
    return
  fi

  mkdir -p $DEST
  cd $DEST

  git clone git@github.com:${GHUSER}/${REPO}.git
}

# Provision
provision() {
  #cd ${DEST}/${REPO}
  #echo "Start provisioning..."
  #ansible-playbook site.yml

  local dir="${DEST}/${REPO}"
  echo "Initialization has completed successfully."
  echo "To start provisioning, run"
  echo
  echo "  \$ cd ${dir}"
  echo '  $ ansible-playbook site.yml'
}

# Run the above functions
run() {
  show_variables
  generate_ssh_key
  prompt_confirmation
  install_xcode
  install_homebrew
  install_packages_for_ansible
  clone_repo
  provision
}

run
