---
- hosts: osx-dev-machine
  roles:
    - role: git
      tags: git
    - role: dotfiles
      tags: dotfiles
    - role: zsh
      tags: zsh
    - role: tmux
      tags: tmux
    - role: vim
      tags: vim
    - role: ruby
      tags: ruby
    - role: vagrant
      tags: vagrant
    - role: homebrew
      tags: homebrew

