---
- name: clone dotfiles repo
  git:
    repo=ssh://git@github.com/{{ dotfiles_repo }}.git
    dest={{ dotfiles_dir }}
  tags: dotfiles-clone

- name: deploy each symlink of dotfiles on $HOME
  command: ./install
    chdir={{ dotfiles_dir }}
    creates=~/.zshrc
  tags: dotfiles-symlink

