---
zsh_plugin_home: ~/.zsh

zsh_prezto_home: ~/.zprezto
zsh_prezto_config_files:
  - zlogin
  - zlogout
  - zprofile
  - zshenv

zsh_plugins:
  - user: zsh-users
    name: zaw
  - user: marzocchi
    name: zsh-notify
