- name: install Python 3
  homebrew:
    name: python3
    state: latest
  tags: python-install

- name: install Python packages
  pip:
    name: '{{ packages }}'
    state: latest
    executable: pip3
  tags: python-package-install
