---
- name: install fzf
  homebrew:
    name: fzf
    state: latest
  register: fzf_status
  tags: fzf-install

- name: install useful key bindings and fuzzy completion
  shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
  when: fzf_status.changed
  tags: fzf-install-extra
