---
- name: update Homebrew itself
  homebrew:
    update_homebrew: yes
  tags: homebrew-update

- name: tap extra repositories
  homebrew_tap:
    tap: '{{ homebrew.taps }}'
    state: present
  tags: homebrew-tap

- name: install Homebrew Casks
  homebrew_cask:
    name: '{{ homebrew.casks }}'
    state: present
  tags: homebrew-cask-install

- name: install Homebrew formula
  homebrew:
    name: '{{ homebrew.formula }}'
    state: latest
  tags: homebrew-install
