---
- name: update Homebrew itself
  homebrew:
    update_homebrew: yes
  tags: homebrew-update

- name: tap extra repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items: '{{ homebrew_repos }}'
  tags: homebrew-tap

- name: install Homebrew Cask packages
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew_cask_packages }}'
  tags: homebrew-cask-install

- name: install Homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages }}'
  tags: homebrew-install
