---
- name: update Homebrew itself
  homebrew:
    update_homebrew: yes
  tags: homebrew-update

- name: tap extra repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items: '{{ homebrew.taps }}'
  tags: homebrew-tap

- name: install Homebrew Casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew.casks }}'
  tags: homebrew-cask-install

- name: install Homebrew formula
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew.formula }}'
  tags: homebrew-install
