---
- name: install Go with cross compilers via Homebrew
  homebrew:
    name=go
    state=latest
    install_options=with-cc-common
  tags: go-install

- name: install packages
  command: go get -u {{ item }}
  with_items: go_pkgs
  tags: go-pkg-install
