---
- name: install Go with cross compilers via Homebrew
  homebrew:
    name: go
    state: latest
    install_options: with-cc-common
  tags: go-install

- name: install packages
  command: 'go get -u {{ item.path }}'
  args:
    # Trim trailing '/...'
    creates: '{{ lookup("env", "GOPATH") }}/src/{{ item.path | regex_replace("/\.\.\.$", "") }}'
  with_items: '{{ go_pkgs }}'
  tags: go-pkg-install
