---
- name: install Go with cross compilers via Homebrew
  homebrew:
    name: go
    state: latest
    install_options: with-cc-common
  tags: go-install

- name: install packages
  command: 'go install {{ item }}@latest'
  args:
    # Trim trailing '/...'
    creates: '{{ lookup("env", "GOPATH") }}/src/{{ item | regex_replace("/\.\.\.$", "") }}'
  with_items: '{{ go.pkgs }}'
  tags: go-pkg-install
