---
- name: create a directory for nvm
  file:
    path: '{{ nvm_home }}'
    state: directory
    mode: '0755'
  tags: nvm-install

- name: install nvm
  shell: curl -o- "{{ nvm_installer_url }}" | bash
  args:
    creates: '{{ nvm_home }}'
    # Ignore warning that says "Use get_url instead of curl!"
    warn: no
  tags: nvm-install

- name: install npm modules
  npm:
    name: '{{ item }}'
    state: latest
    global: yes
  with_items: '{{ node_modules }}'
  tags: npm-install
