---
- name: install nodebrew
  shell: curl -L "{{ nodebrew_url }}" | perl - setup
  args:
    creates: '{{ nodebrew_home }}/nodebrew'
  tags: nodebrew-install

- name: install npm modules
  npm:
    name: '{{ item }}'
    state: latest
    global: yes
  with_items: '{{ node_modules }}'
  tags: npm-install
