---
vim:
  home: ~/.vim
  dirs:
    - autoload
    - colors
  color_schemes:
    # Molokai
    - url: https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim
      file: molokai.vim

vim_plug:
  url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  file: plug.vim
  home: '{{ vim.home }}/plugged'
