---
- name: install Lua-enabled Vim via Homebrew
  homebrew:
    name: vim
    state: latest
    install_options: with-lua,with-python3
  tags: vim-install

# Install color schemes
- name: create colors directory
  file:
    path: '{{ vim.dir.colors }}'
    state: directory
    mode: 0755
    recurse: yes
  tags: vim-install-color-schemes

- name: install color schemes
  get_url:
    url: '{{ item.url }}'
    dest: '{{ vim.dir.colors }}/{{ item.file }}'
  with_items: '{{ vim.color_schemes }}'
  tags: vim-install-color-scheme

# Install Vim-Plug
- name: create autoload directory
  file:
    path: '{{ vim.dir.autoload }}'
    state: directory
    mode: 0755
    recurse: yes
  tags: vim-install-plug

- name: install Vim-Plug
  get_url:
    url: '{{ vim_plug.url }}'
    dest: '{{ vim.dir.autoload }}/{{ vim_plug.file }}'
  tags: vim-install-plug

# Install plugins
- name: install plugins
  command: vim +PlugInstall +qall
  args:
    creates: '{{ vim_plug.home }}'
  tags: vim-install-plugins
