---
- name: install Lua-enabled Vim via Homebrew
  homebrew:
    name: vim
    state: latest
    install_options: with-lua,with-python3
  tags: vim-install

# Install color scheme
- name: create colors directory
  file:
    path: '{{ vim_home }}/colors'
    state: directory
    mode: 0755
    recurse: yes
  tags: vim-install-color-scheme

- name: download color scheme file
  get_url:
    url: '{{ vim_color_scheme.url }}'
    dest: '{{vim_home}}/colors/{{ vim_color_scheme.name }}'
  tags: vim-install-color-scheme

# Install Vim-Plug
- name: create autoload directory
  file:
    path: '{{ vim_home }}/autoload'
    state: directory
    mode: 0755
    recurse: yes
  tags: vim-install-plug

- name: install Vim-Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ vim_home }}/autoload/plug.vim'
  tags: vim-install-plug

# Install plugins
- name: install Vim plugins
  command: vim +PlugInstall +qall
  args:
    creates: '{{ vim_plug_home }}'
  tags: vim-install-plugins
