---
- name: install Lua-enabled Vim via Homebrew
  homebrew:
    name: vim
    state: latest
    install_options: with-lua,with-python3
  tags: vim-install

# Install color scheme
- name: create colors directory
  file:
    path: '{{ vim_home }}/colors'
    state: directory
    mode: 0755
  tags: vim-install-color-scheme

- name: download color scheme file
  get_url:
    url: '{{ vim_color_scheme.url }}'
    dest: '{{vim_home}}/colors/{{ vim_color_scheme.name }}'
  tags: vim-install-color-scheme

# Install Vim-Plug
- name: create autoload directory
  file:
    path: '{{ vim_home }}/autoload'
    state: directory
    mode: 0755
  tags: vim-install-plug

- name: install Vim-Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ vim_home }}/autoload/plug.vim'
  tags: vim-install-plug

# Install plugins
- name: install plugins
  command: vim +PlugInstall +qall
  tags: vim-install-plugins

# Build vimproc.vim if the plugin directory exists
- stat:
    path: '{{ vimproc_home }}'
  register: st
  tags: vim-build-vimproc

- name: Build vimproc
  command: make
  args:
    chdir: '{{ vimproc_home }}'
    creates: '{{ vimproc_home }}/autoload/{{ vimproc_so }}'
  tags: vim-build-vimproc

