---
- name: create autoload directory
  file:
    path={{ vim_home }}/autoload
    state=directory

- name: install Vim-Plug
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest={{ vim_home }}/autoload/plug.vim

# Build vimproc.vim if the plugin directory exists
- stat: path={{ vimproc_home }}
  register: st
- name: Build vimproc
  command: make
    chdir={{ vimproc_home }}
    creates={{ vimproc_home }}/autoload/{{ vimproc_so }}
  when: st.stat.exists == True

