---
- name: install Lua-enabled Vim via Homebrew
  homebrew:
    name: vim
    state: latest
    install_options: with-lua,with-python3
  tags: vim-install

- name: prepare necessary directories
  file:
    path: '{{ vim.home }}/{{ item }}'
    state: directory
    recurse: yes
    mode: 0755
  with_items: '{{ vim.dirs }}'
  tags: vim-prepare-dirs

- name: install color schemes
  get_url:
    url: '{{ item.url }}'
    dest: '{{ vim.home }}/colors/{{ item.file }}'
  with_items: '{{ vim.color_schemes }}'
  tags: vim-install-color-scheme

- name: install Vim-Plug
  get_url:
    url: '{{ vim_plug.url }}'
    dest: '{{ vim.home }}/autoload/{{ vim_plug.file }}'
  tags: vim-install-plug

- name: install plugins
  command: vim +PlugInstall +qall
  args:
    creates: '{{ vim_plug.home }}'
  tags: vim-install-plugins
