---
- name: install Neovim via Homebrew
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items:
    - neovim
    - python3
  tags: neovim-install

- name: install Python provider
  pip:
    name: neovim
    state: latest
    executable: pip3
  tags: neovim-install-python

- name: install Ruby provider
  gem:
    name: neovim
    state: latest
  tags: neovim-install-ruby

- name: install Node provider
  npm:
    name: neovim
    state: latest
    global: yes
  tags: neovim-install-node

- name: prepare necessary directories
  file:
    path: '{{ item }}'
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - '{{ neovim.autoload }}'
    - '{{ neovim.colors }}'
  tags: neovim-prepare-dirs

- name: install color schemes
  get_url:
    url: '{{ item.url }}'
    dest: '{{ neovim.colors }}/{{ item.file }}'
  with_items: '{{ neovim.color_schemes }}'
  tags: neovim-install-color-scheme

- name: install Python client for Neovim
  pip:
    name: neovim
    state: latest
    executable: pip3
  tags: neovim-install-python

- name: install Vim-Plug
  get_url:
    url: '{{ vim_plug.url }}'
    dest: '{{ neovim.autoload }}/{{ vim_plug.file }}'
  tags: neovim-install-plug

- name: install plugins
  command: nvim +PlugInstall +qall
  args:
    creates: '{{ vim_plug.home }}'
  tags: neovim-install-plugins
